jupyter_book_task:
  auto_cancellation: true
  container:
    image: python:3.10.5-slim
    cpu: 2
    memory: 8G
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script: echo $PYTHON_VERSION && cat requirements.txt .ci/requirements.txt
    populate_script: pip install -r requirements.txt -r .ci/requirements.txt

  build_script: |
    jupyter-book build docs -v
  # pages_script: |
  #   if [[ $CIRRUS_BRANCH == "main" ]]; then
  #     ghp-import -n docs/_build/html
  #     git push -fq https://${GH_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git gh-pages
  #   fi
